language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

before_install: gem install bundler

addons:
   code_climate:
     repo_token: aaa2bcd71ac641474a13caabe294beeb26abcc7c4dd82f3395a7b9193bb20d02
